Upgrade couchbase-java-client to 2.5.7
The couchbase-java-client change DefaultCouchbaseEnvironment class signature. So we need to recompile testcontainers-java-module-couchbase over this new version for avoid this exception:

Fix java.lang.NoSuchMethodError: com.couchbase.client.java.env.DefaultCouchbaseEnvironment$Builder.bootstrapCarrierDirectPort(I)Lcom/couchbase/client/java/env/DefaultCouchbaseEnvironment$Builder;